configured_endpoints: 38
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nvidia-ishandhanani%2Fnvidia-cloud-functions-add37b001ffc096dca1b8c2df1584c80f9eecd0acdd246914c717d5b7ee69ad6.yml
